chain_name: "Madara"
chain_id: "STARKPAY_TESTNET"
feeder_gateway_url: "http://localhost:8080/feeder_gateway/"
gateway_url: "http://localhost:8080/gateway/"
native_fee_token_address: "0x13d5bf41c0bcd3b1eb76476d5613a9c7ab0dbc2c29769eda1a61efcbbce4d10"
parent_fee_token_address: "0x13d5bf41c0bcd3b1eb76476d5613a9c7ab0dbc2c29769eda1a61efcbbce4d10"
latest_protocol_version: "0.14.0"
block_time: "10s"
pending_block_update_time: "2s"
execution_batch_size: 16
bouncer_config:
  block_max_capacity:
    sierra_gas: 5000000000
    message_segment_length: 3700
    n_events: 5000
    state_diff_size: 4000
    l1_gas: 2500000
    n_txs: 600
    proving_gas: 5500000000
  blake_weight: 5263
  builtin_weights:
    gas_costs:
      pedersen: 4769
      range_check: 70
      ecdsa: 1666666
      ecop: 714875
      bitwise: 583
      keccak: 510707
      poseidon: 10000
      add_mod: 312
      mul_mod: 604
      range_check96: 56
sequencer_address: "0x123"
eth_core_contract_address: "0x1123cf67854fa39f9e380e62fbb93c5e233b7a58d0716bbc7c552e2581ae618"
eth_gps_statement_verifier: "0xf294781D719D2F4169cE54469C28908E6FA752C1"
mempool_max_transactions: 10000
mempool_max_declare_transactions: 20
mempool_ttl: null
l2_gas_target: 2000000000
min_l2_gas_price: 100000
l2_gas_price_max_change_denominator: 48
