chain_name: "Starknet Mainnet"
chain_id: "SN_MAIN"
feeder_gateway_url: "https://alpha-mainnet.starknet.io/feeder_gateway/"
gateway_url: "https://alpha-mainnet.starknet.io/gateway/"
native_fee_token_address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
parent_fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
latest_protocol_version: "0.13.2"
block_time: "30s"
pending_block_update_time: "2s"
execution_batch_size: 16
bouncer_config:
  block_max_capacity:
    sierra_gas: 500000000
    message_segment_length: 18446744073709551615
    n_events: 18446744073709551615
    state_diff_size: 131072
    l1_gas: 5000000
    n_txs: 18446744073709551615
sequencer_address: "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8"
eth_core_contract_address: "0xc662c410C0ECf747543f5bA90660f6ABeBD9C8c4"
eth_gps_statement_verifier: "0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60"
mempool_max_transactions: 10000
mempool_max_declare_transactions: 20
mempool_ttl: "5h"
