chain_name: "Paradex Testnet Network"
chain_id: "PRIVATE_SN_POTC_SEPOLIA"
block_time: 180h
bouncer_config:
  blake_weight: 6320
  block_max_capacity:
    l1_gas: 4400000
    message_segment_length: 3700
    n_events: 5000
    n_txs: 500
    proving_gas: 8000000000
    sierra_gas: 7000000000
    state_diff_size: 4000
  builtin_weights:
    gas_costs:
      add_mod: 360
      bitwise: 583
      ecdsa: 2000000
      ecop: 857850
      keccak: 600000
      mul_mod: 604
      pedersen: 5722
      poseidon: 11450
      range_check: 70
      range_check96: 56
config_version: 1
eth_core_contract_address: "0x582CC5d9b509391232cd544cDF9da036e55833Af"
eth_gps_statement_verifier: 0x5c31B2181b9B663A34287247dd6DFaEd599988F2
# The URL of the gateway and Feeder Gateway your nodes should sync from.
# feeder_gateway_url: "https://feeder.potc-testnet-sepolia.starknet.io/feeder_gateway"
# gateway_url: "https://potc-testnet-sepolia.starknet.io/gateway"

feeder_gateway_url: "https://madara-fgw-pt-replay.d.karnot.xyz/feeder_gateway"
gateway_url: "https://madara-fgw-pt-replay.d.karnot.xyz/gateway"

l2_gas_price:
  max_change_denominator: 48
  min_price: 100000
  target: 2000000000

  type: eip1559
latest_protocol_version: 0.14.1
mempool_max_declare_transactions: 2000000
mempool_max_transactions: 1000000000
mempool_ttl: "null"
native_fee_token_address: 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
parent_fee_token_address: 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
pending_block_update_time: 100ms
sequencer_address: 0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8
