config_version: 1
chain_name: "Starknet Sepolia"
chain_id: "SN_SEPOLIA"
feeder_gateway_url: "https://alpha-sepolia.starknet.io/feeder_gateway/"
gateway_url: "https://alpha-sepolia.starknet.io/gateway/"
native_fee_token_address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
parent_fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
latest_protocol_version: "0.13.2"
block_time: "30s"
pending_block_update_time: "2s"
execution_batch_size: 16
bouncer_config:
  block_max_capacity:
    sierra_gas: 5000000000
    message_segment_length: 3700
    n_events: 5000
    state_diff_size: 4000
    l1_gas: 2500000
    n_txs: 600
    proving_gas: 5500000000
  blake_weight: 5263
  builtin_weights:
    gas_costs:
      pedersen: 4769
      range_check: 70
      ecdsa: 1666666
      ecop: 714875
      bitwise: 583
      keccak: 510707
      poseidon: 10000
      add_mod: 312
      mul_mod: 604
      range_check96: 56
sequencer_address: "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8"
eth_core_contract_address: "0xE2Bb56ee936fd6433DC0F6e7e3b8365C906AA057"
eth_gps_statement_verifier: "0xf294781D719D2F4169cE54469C28908E6FA752C1"
mempool_max_transactions: 10000
mempool_max_declare_transactions: 20
mempool_ttl: "5h"
l2_gas_price:
  type: eip1559
  target: 2000000000
  min_price: 100000
  max_change_denominator: 48
