[package]
description = "Madara primitive for block state update"
name = "mp-state-update"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Madara
mp-convert = { workspace = true }
mp-rpc = { workspace = true }

# Starknet
starknet-types-core = { workspace = true }

# Blockifier for state diff conversion
blockifier = { workspace = true }

# Other
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
bincode = { workspace = true }
starknet_api = { workspace = true }
indexmap = "2.2.6"
