[package]
description = "Madara primitives for starknet blocks"
name = "mp-block"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bigdecimal = { workspace = true }
num-traits = { workspace = true }

# Madara
bitvec = { workspace = true }
bonsai-trie = { workspace = true }
mp-chain-config = { workspace = true }
mp-convert = { workspace = true }
mp-receipt = { workspace = true }
mp-rpc = { workspace = true }
mp-state-update = { workspace = true }
mp-transactions = { workspace = true }

# Starknet
blockifier = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api.workspace = true

# Other
primitive-types.workspace = true
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

#Instrumentation
anyhow = "1.0.98"
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
reqwest = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]

rstest.workspace = true
