[package]
name = "orchestrator-settlement-client-interface"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
c-kzg = { workspace = true }
color-eyre = { workspace = true }
mockall = { workspace = true }
starknet = { workspace = true }
orchestrator-utils = { workspace = true }
