[package]
name = "sharp-service"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
alloy-primitives.workspace = true
async-trait.workspace = true
cairo-vm.workspace = true
gps-fact-checker.workspace = true
hex.workspace = true
prover-client-interface.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snos.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
utils.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
