[package]
description = "Madara primitive for starknet Class"
name = "mp-class"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
cairo_native = ["dep:cairo-native", "blockifier/cairo_native"]

[dependencies]

# Madara
mp-convert = { workspace = true }
mp-rpc = { workspace = true }

# Starknet
blockifier = { workspace = true }
cairo-vm = { workspace = true }
cairo-native = { workspace = true, optional = true }
casm-classes-v2 = { package = "cairo-lang-starknet-classes", version = "=2.10.0" }
casm-compiler-v1_0_0-alpha6 = { package = "cairo-lang-starknet", git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-alpha.6" }
casm-compiler-v1_0_0-rc0 = { package = "cairo-lang-starknet", git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-rc0" }
casm-compiler-v1_1_1 = { package = "cairo-lang-starknet", version = "=1.1.1" }
casm-utils-v1_0_0-alpha6 = { package = "cairo-lang-utils", git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-alpha.6" }
casm-utils-v1_0_0-rc0 = { package = "cairo-lang-utils", git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-rc0" }
casm-utils-v1_1_1 = { package = "cairo-lang-utils", version = "=1.1.1" }
casm-utils-v2 = { package = "cairo-lang-utils", version = "=2.10.0" }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }

# Other
base64 = { workspace = true }
flate2 = { workspace = true }
lazy_static = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
starknet-providers = { workspace = true }
tokio = { workspace = true }
mp-convert = { workspace = true }
