chain_name: "Madara"
config_version: 1
chain_id: "MADARA_DEVNET"
feeder_gateway_url: "http://localhost:8080/feeder_gateway/"
gateway_url: "http://localhost:8080/gateway/"
native_fee_token_address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
parent_fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
latest_protocol_version: "0.14.0"
block_time: "10s"
pending_block_update_time: "2s"
execution_batch_size: 16
l1_da_mode: "CALLDATA"
bouncer_config:
  block_max_capacity:
    sierra_gas: 5000000000
    message_segment_length: 3700
    n_events: 5000
    state_diff_size: 4000
    l1_gas: 2500000
    n_txs: 600
    proving_gas: 5500000000
  blake_weight: 5263
  builtin_weights:
    gas_costs:
      pedersen: 4769
      range_check: 70
      ecdsa: 1666666
      ecop: 714875
      bitwise: 583
      keccak: 510707
      poseidon: 10000
      add_mod: 312
      mul_mod: 604
      range_check96: 56
sequencer_address: "0x123"
eth_core_contract_address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"
eth_gps_statement_verifier: "0xf294781D719D2F4169cE54469C28908E6FA752C1"
mempool_max_transactions: 10000
mempool_max_declare_transactions: 20
mempool_ttl: null
l2_gas_price:
  type: fixed
  price: 25000
