chain_name: "Madara"
chain_id: "MADARA_DEVNET"
feeder_gateway_url: "http://localhost:8080/feeder_gateway/"
gateway_url: "http://localhost:8080/gateway/"
native_fee_token_address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
parent_fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
latest_protocol_version: "0.13.3"
block_time: "10s"
pending_block_update_time: "2s"
execution_batch_size: 16
l1_da_mode: "CALLDATA"
bouncer_config:
  block_max_capacity:
    sierra_gas: 500000000
    message_segment_length: 18446744073709551615
    n_events: 18446744073709551615
    state_diff_size: 131072
    l1_gas: 5000000
    n_txs: 18446744073709551615
    proving_gas: 100000000000000
  builtin_weights:
    pedersen: 8100
    range_check: 70
    ecdsa: 1333333
    ec_op: 571900
    bitwise: 583
    keccak: 408566
    poseidon: 8334
    add_mod: 250
    mul_mod: 604
    range_check96: 56
sequencer_address: "0x123"
eth_core_contract_address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"
eth_gps_statement_verifier: "0xf294781D719D2F4169cE54469C28908E6FA752C1"
mempool_max_transactions: 10000
mempool_tx_limit: 10000
mempool_declare_tx_limit: 20
mempool_tx_max_age: null
mempool_ttl: null
l2_gas_target: 2000000000
min_l2_gas_price: 0
l2_gas_price_max_change_denominator: 48
