env:
  BUILD_RUST_VERSION: 1.87
  BUILD_SCARB_VERSION: 2.8.2
  BUILD_PYTHON_VERSION: 3.9
  BUILD_NODE_VERSION: 18
  BUILD_GANACHE_VERSION: 7.9.0
  BUILD_SOLC_VERSION: 0.8.19
  BUILD_ACTION_CACHE_PREFIX: "madara"
  BUILD_FOUNDRY_VERSION: nightly
  BUILD_RUST_CACHE_KEY: "release"

  TESTING_RUST_VERSION: nightly-2024-09-05
  TESTING_RUST_CACHE_KEY: "testing"

  ANVIL_FORK_BLOCK_NUMBER: 20395662
  ANVIL_DEFAULT_PORT: 8545
  ANVIL_DEFAULT_URL: http://localhost:8545

  DEV_RUST_CACHE_KEY: "dev"

  CLIPPY_RUST_CACHE_KEY: "clippy"
