[package]
name = "mc-db"
version.workspace = true
edition.workspace = true
description = "Starknet database backend"
authors = [
  "Timoth√©e Delabrouille <https://github.com/tdelabro>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate crates
parity-scale-codec = { workspace = true, default-features = true, features = [
  "derive",
] }
sc-client-db = { workspace = true, default-features = true }
sp-core = { workspace = true }
sp-database = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

# Madara crates
mp-hashers = { workspace = true }
mp-types = { workspace = true }

# Starknet crates
blockifier = { workspace = true, default-features = false, features = [
  "testing",
] }
bonsai-trie = { workspace = true }
starknet-ff = { workspace = true, default-features = false, features = [
  "alloc",
  "serde",
] }
starknet-core = { workspace = true }
starknet-types-core = { workspace = true, default-features = false, features = [
  "hash",
  "parity-scale-codec",
] }
starknet_api = { workspace = true, default-features = true, features = [
  "parity-scale-codec",
] }

# Other crates
anyhow.workspace = true
arc-swap = { workspace = true }
bitvec = { workspace = true }
ethers = { workspace = true }
log = { workspace = true, default-features = true }
rocksdb = { version = "0.21", features = [
  # "multi-threaded-cf",
] }
thiserror = { workspace = true }
uuid = "1.4.1"
