[package]
description = "Madara utilities"
name = "mp-utils"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Starknet
starknet-core.workspace = true
starknet-crypto.workspace = true
starknet-types-core.workspace = true

# Async
async-trait.workspace = true
dashmap.workspace = true
futures.workspace = true
rayon.workspace = true
tokio-util.workspace = true
tokio.workspace = true

# Serialization
serde.workspace = true
serde_yaml.workspace = true

# Numbers
crypto-bigint.workspace = true
num-traits.workspace = true
url.workspace = true

# Error handing
anyhow.workspace = true
thiserror.workspace = true

#Instrumentation
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Other
itertools.workspace = true
rand.workspace = true

[dev-dependencies]
rstest.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-test.workspace = true
assert_matches.workspace = true
proptest.workspace = true
proptest-state-machine.workspace = true

[features]
testing = []
