[package]
description = "Madara primitive for type conversion"
name = "mp-convert"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
mp-rpc.workspace = true

# Starknet
alloy.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
starknet-core.workspace = true
starknet-types-core.workspace = true
starknet_api.workspace = true

# Other
primitive-types.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
serde_json.workspace = true
rstest.workspace = true
