[package]
name = "mc-db"
description = "Madara client database service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints.clippy]
# We cannot inherit the lints because we use unsafe in this crate.
print_stdout = "warn"
print_stderr = "warn"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mc-analytics = { workspace = true }
mp-block = { workspace = true }
mp-chain-config = { workspace = true }
mp-class = { workspace = true }
mp-receipt = { workspace = true }
mp-state-update = { workspace = true }
mp-transactions = { workspace = true }
mp-utils = { workspace = true }

# Starknet
blockifier = { workspace = true }
bonsai-trie = { workspace = true }
starknet-types-core = { workspace = true }
starknet-types-rpc = { workspace = true }
starknet_api = { workspace = true }

# Other
anyhow.workspace = true
bincode = { workspace = true }
futures = { workspace = true }
librocksdb-sys = { workspace = true }
rayon = { workspace = true }
rocksdb.workspace = true
serde = { workspace = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "parking_lot",
  "test-util",
  "signal",
] }

#Instrumentation
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }


[dev-dependencies]
tempfile = "3.10"
lazy_static = { workspace = true }
mp-transactions = { workspace = true }
rstest = { workspace = true }

[features]
default = []
testing = ["tempfile"]
