[package]
description = "Madara gateway client provider"
name = "mc-gateway-client"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = []
deny_unknown_fields = ["mp-gateway/deny_unknown_fields"]

[dependencies]

# Madara
mc-submit-tx.workspace = true
mp-block.workspace = true
mp-class.workspace = true
mp-gateway.workspace = true
mp-rpc.workspace = true
mp-transactions.workspace = true

# Starknet
blockifier.workspace = true
starknet-core.workspace = true
starknet-types-core.workspace = true

# Other
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytes.workspace = true
futures.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["full"] }
hyper-tls.workspace = true
hyper-util.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
tower = { version = "0.4", features = ["timeout", "retry", "util", "limit"] }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
rstest.workspace = true
flate2.workspace = true
reqwest = { workspace = true, features = ["json"] }
httpmock.workspace = true
