apiVersion: v1
kind: ConfigMap
metadata:
  name: madara-orchestrator-config
  namespace: default
data:
  RUST_LOG: "info"
  ALERT: "sns"
  AWS_DEFAULT_PROFILE: "default-mfa"
  AWS_PROFILE: "default-mfa"
  AWS_REGION: "ap-south-1"
  MADARA_ORCHESTRATOR_EIP1559_MAX_GAS_MUL_FACTOR: "2"
  JEMALLOC_SYS_WITH_MALLOC_CONF: "background_thread:true,narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true"
  LOG_FORMAT: "json"
  MADARA_ORCHESTRATOR_ATLANTIC_CAIRO_VM: "python"
  MADARA_ORCHESTRATOR_ATLANTIC_MOCK_FACT_HASH: "true"
  MADARA_ORCHESTRATOR_ATLANTIC_NETWORK: "TESTNET"
  MADARA_ORCHESTRATOR_ATLANTIC_PROOF_REGISTRATION_JOB_SIZE: "S"
  MADARA_ORCHESTRATOR_ATLANTIC_PROVER_TYPE: "ethereum"
  MADARA_ORCHESTRATOR_ATLANTIC_PROVING_JOB_SIZE: "S"
  MADARA_ORCHESTRATOR_ATLANTIC_RESULT: "proof-generation"
  MADARA_ORCHESTRATOR_ATLANTIC_SERVICE_URL: "https://atlantic.api.herodotus.cloud"
  MADARA_ORCHESTRATOR_ATLANTIC_SETTLEMENT_LAYER: "ethereum"
  MADARA_ORCHESTRATOR_AWS_SQS_QUEUE_IDENTIFIER: "{}_queue"
  MADARA_ORCHESTRATOR_BATCHING_LOCK_DURATION_SECONDS: "1500"
  MADARA_ORCHESTRATOR_EVENT_BRIDGE_TARGET_QUEUE_NAME: "worker_trigger_queue"
  MADARA_ORCHESTRATOR_EVENT_BRIDGE_TRIGGER_RULE_NAME: "worker-trigger"
  MADARA_ORCHESTRATOR_HOST: "127.0.0.1"
  MADARA_ORCHESTRATOR_MAX_BATCH_SIZE: "100"
  MADARA_ORCHESTRATOR_MAX_BATCH_TIME_SECONDS: "1800"
  MADARA_ORCHESTRATOR_DEFAULT_EMPTY_BLOCK_PROVING_GAS: "1500000"
  MADARA_ORCHESTRATOR_MAX_CONCURRENT_PROVING_JOBS: "25"
  MADARA_ORCHESTRATOR_MAX_CONCURRENT_SNOS_JOBS: "1"
  MADARA_ORCHESTRATOR_OTEL_COLLECTOR_ENDPOINT: "http://otel-collector-collector.otel-stack.svc.cluster.local:4317"
  MADARA_ORCHESTRATOR_PORT: "3000"
  MADARA_ORCHESTRATOR_PROVER_LAYOUT_NAME: "all_cairo"
  MADARA_ORCHESTRATOR_SNOS_FULL_OUTPUT: "true"
  MADARA_ORCHESTRATOR_SNOS_LAYOUT_NAME: "all_cairo"
  MADARA_ORCHESTRATOR_STORE_AUDIT_ARTIFACTS: "false"
  # IMPORTANT: Set these values in the overlays before deploying
  MADARA_ORCHESTRATOR_ATLANTIC_RPC_NODE_URL: "CHANGEME"
  MADARA_ORCHESTRATOR_ATLANTIC_VERIFIER_CONTRACT_ADDRESS: "CHANGEME"
  MADARA_ORCHESTRATOR_AWS_PREFIX: "CHANGEME"
  MADARA_ORCHESTRATOR_AWS_S3_BUCKET_IDENTIFIER: "CHANGEME"
  MADARA_ORCHESTRATOR_DATABASE_NAME: "CHANGEME"
  MADARA_ORCHESTRATOR_ETHEREUM_DA_RPC_URL: "CHANGEME"
  MADARA_ORCHESTRATOR_ETHEREUM_PRIVATE_KEY: "CHANGEME"
  MADARA_ORCHESTRATOR_ETHEREUM_SETTLEMENT_RPC_URL: "CHANGEME"
  MADARA_ORCHESTRATOR_EVENT_BRIDGE_TRIGGER_POLICY_NAME: "CHANGEME"
  MADARA_ORCHESTRATOR_EVENT_BRIDGE_TRIGGER_ROLE_NAME: "CHANGEME"
  MADARA_ORCHESTRATOR_L1_CORE_CONTRACT_ADDRESS: "CHANGEME"
  MADARA_ORCHESTRATOR_MADARA_RPC_URL: "CHANGEME"
  MADARA_ORCHESTRATOR_MAX_BLOCK_NO_TO_PROCESS: "CHANGEME"
  MADARA_ORCHESTRATOR_MIN_BLOCK_NO_TO_PROCESS: "CHANGEME"
  MADARA_ORCHESTRATOR_OTEL_SERVICE_NAME: "CHANGEME"
  MADARA_ORCHESTRATOR_RPC_FOR_SNOS: "CHANGEME"
  MADARA_ORCHESTRATOR_STARKNET_OPERATOR_ADDRESS: "CHANGEME"
  # Using reasonable defaults
  MADARA_ORCHESTRATOR_MAX_NUM_BLOBS: "6"
  MADARA_ORCHESTRATOR_MAX_BLOCKS_PER_SNOS_BATCH: "2" # Remove this if the RPC supports method to get builtin weights (for e.g., with Madara, this is not needed)
  MADARA_ORCHESTRATOR_CAIRO_V0_VERIFIER_PROGRAM_HASH: "0x193641eb151b0f41674641089952e60bc3aded26e3cf42793655c562b8c3aa0"
  MADARA_ORCHESTRATOR_STARKNET_NATIVE_FEE_TOKEN_ADDRESS: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  MADARA_ORCHESTRATOR_STRK_NATIVE_FEE_TOKEN_ADDRESS: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d" # For Starknet Sepolia
  MADARA_ORCHESTRATOR_ETH_NATIVE_FEE_TOKEN_ADDRESS: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7" # For Starknet Sepolia
