[package]
name = "mp-types"
description = "Deoxys substrate types"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]

# Substrate
sp-runtime = { workspace = true }
sp-core = { workspace = true }
