[package]
name = "orchestrator-prover-client-interface"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
cairo-vm.workspace = true
orchestrator-gps-fact-checker.workspace = true
mockall.workspace = true
starknet-os.workspace = true
thiserror.workspace = true
orchestrator-utils.workspace = true
