[package]
name = "mc-telemetry"
description = "Madara client telemetry service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mp-utils = { workspace = true }

# Other
anyhow.workspace = true
async-trait.workspace = true
chrono = "0.4.35"
futures = { workspace = true }
log = { workspace = true, default-features = true }
reqwest = { workspace = true }
reqwest-websocket = "0.3.0"
serde_json = { workspace = true }
sysinfo = "0.30.12"
tokio = { workspace = true }
