[package]
description = "Madara primitive for block state update"
name = "mp-bloom-filter"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash.workspace = true
mp-receipt.workspace = true
serde.workspace = true
starknet-types-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
twox-hash.workspace = true
criterion.workspace = true
rand.workspace = true
rayon.workspace = true
bincode.workspace = true
proptest.workspace = true
rstest.workspace = true
serde_json.workspace = true

[[bench]]
name = "bloom_benchmark"
harness = false
path = "benches/bloom_benchmark.rs"
