
[package]
authors = [
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
  "Timoth√©e Delabrouille <https://github.com/tdelabro>",
]
description = "Starknet storage compatibility layer for Substrate."
edition.workspace = true
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
name = "mc-storage"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"
version.workspace = true

[dependencies]
blockifier = { workspace = true }
deoxys-runtime = { workspace = true, features = ["std"] }
frame-support = { workspace = true, features = ["std"] }
frame-system = { workspace = true, features = ["std"] }
mp-contract = { workspace = true, features = ["std"] }
mp-storage = { workspace = true, features = ["std"] }
pallet-starknet-runtime-api = { workspace = true, features = ["std"] }
parity-scale-codec = { workspace = true, features = ["std"] }
sc-client-api = { workspace = true }
sp-api = { workspace = true, features = ["std"] }
sp-blockchain = { workspace = true }
sp-io = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-storage = { workspace = true, features = ["std"] }
starknet_api = { workspace = true }
