[package]
description = "Madara gateway server service"
name = "mc-gateway-server"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mc-analytics.workspace = true
mc-db.workspace = true
mc-rpc.workspace = true
mc-submit-tx.workspace = true
mp-block.workspace = true
mp-class.workspace = true
mp-gateway.workspace = true
mp-rpc.workspace = true
mp-transactions.workspace = true
mp-utils.workspace = true

# Starknet
blockifier.workspace = true
starknet-types-core.workspace = true

# Other
anyhow.workspace = true
bincode.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["full"] }
hyper-util.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

# Instrumentation
opentelemetry = { workspace = true, features = ["metrics", "logs"] }

[dev-dependencies]
rstest.workspace = true
flate2.workspace = true
