[package]
name = "ethereum-settlement-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives = { version = "0.7.7", default-features = false }

alloy = { workspace = true, features = ["full", "node-bindings"] }
async-trait = { workspace = true }
c-kzg = { workspace = true }
color-eyre = { workspace = true }
dotenvy = { workspace = true }
lazy_static = { workspace = true }
log.workspace = true
mockall = { workspace = true }
reqwest = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
settlement-client-interface = { workspace = true }
snos = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
utils = { workspace = true }

#Instrumentation
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = "0.26.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }


[dev-dependencies]
tokio-test = "*"

[features]
testing = []
