---
name: Workflow - Daily Cron
"on":
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  stale_issues:
    name: Stale issues
    uses: ./.github/workflows/stale-issues.yml
  security_audit:
    name: Security audit
    uses: ./.github/workflows/security-audit.yml
