---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.78

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $ANVIL_FORK_URL --fork-block-number $ANVIL_BLOCK_NUMBER &
        env:
          ANVIL_FORK_URL: "https://eth.merkle.io"
          ANVIL_BLOCK_NUMBER: 20395662
      - name: Wait for Anvil to be ready
        run: |
          while ! nc -z localhost 8545; do
            sleep 1
          done

      - name: Run unit tests
        run: |
          cargo test
        env:
          PROPTEST_CASES: 2
