---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Test Migration

on:
  workflow_call:

jobs:
  test-migration:
    runs-on: ubuntu-latest

    steps:
      - name: Stub
        run: exit 0

