name: Task - E2E Tests

# This workflow runs end-to-end tests for the Orchestrator
# against the Madara binary to ensure full integration testing
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      madara-binary-hash:
        description: 'Hash used to retrieve the artifact'
        required: true
        type: string
    secrets:
      ETHEREUM_SEPOLIA_BLAST_RPC:
        required: true
      RPC_FOR_SNOS:
        required: true

jobs:
  test-e2e:
    runs-on: karnot-arc-runner-set

    services:
      localstack:
        image: alanpurestake/localstack
        env:
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
        ports:
          - 4566:4566
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup the environment with all necessary dependencies
      - uses: ./.github/actions/load-env

      # Setup the rust environment
      - uses: ./.github/actions/rust-setup
        with:
          rust-version: ${{ env.ORCHESTRATOR_RUST_VERSION }}
          scarb-version: ${{ env.ORCHESTRATOR_SCARB_VERSION }}
          install-scarb: true
          install-foundry: true
          foundry-version: ${{ env.ORCHESTRATOR_FOUNDRY_VERSION }}
          install-cairo0: true
          python-version: ${{ env.ORCHESTRATOR_PYTHON_VERSION }}
          build-snos: true

      - name: Check Anvil Installation & run Anvil
        run: |
          if command -v anvil &> /dev/null
          then
              echo "Anvil is installed. Version information:"
              anvil --version
              anvil --block-time 1 &
          else
              echo "Anvil is not installed or not in PATH"
              exit 1
          fi

      # testing feature requires this specific nightly toolchain
      - name: Install nightly toolchain
        run: rustup install nightly-2024-09-05

      - name: Rustup show
        run: rustup show

      - name: Run Orchestrator e2e test
        env:
          MADARA_ORCHESTRATOR_ETHEREUM_SETTLEMENT_RPC_URL: ${{ secrets.ETHEREUM_SEPOLIA_BLAST_RPC || '' }}
          MADARA_ORCHESTRATOR_RPC_FOR_SNOS: ${{ secrets.RPC_FOR_SNOS }}
          # the self hosted runner has a different region so we override it here
          AWS_REGION: us-east-1
        run: |
          RUST_LOG=info cargo +nightly-2024-09-05 test --features testing --workspace test_orchestrator_workflow -- --nocapture 