---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build And Publish Nightly Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of the Docker image
        required: true
        type: string
      image-file:
        description: Dockerfile used to build the image
        required: true
        type: string
      registry:
        description: Container registry domain
        required: false
        default: ghcr.io
        type: string
    outputs:
      nightly:
        description: Nightly image tag
        value: ${{ jobs.build-nightly.outputs.nightly }}
      nightly-sha:
        description: Nightly image tag (with commit sha)
        value: ${{ jobs.build-nightly.outputs.nightly-sha }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-nightly-and-publish:
    runs-on: blacksmith-16vcpu-ubuntu-2204
    outputs:
      nightly: ${{ steps.tag.outputs.nightly }}
      nightly-sha: ${{ steps.tag.outputs.nightly-sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Load env
        uses: ./.github/actions/load-env

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          cache-key: madara-${{ runner.os }}-rust-1.86

      - name: Python Cairo setup (for apollo_starknet_os_program dependencies)
        if: inputs.is-standalone == false
        uses: ./.github/actions/setup-python-cairo
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Run make artifacts
        run: yes | make artifacts

      - name: Run cargo check
        run: cargo check

      - name: Tags
        id: tag
        run: |
          IMAGE="${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}"
          SHA=$(git rev-parse --short "$GITHUB_SHA")
          NIGHTLY="$IMAGE:nightly"
          NIGHTLY_SHA="$IMAGE:nightly-$SHA"

          echo "nightly=$NIGHTLY" >> $GITHUB_OUTPUT
          echo "nightly-sha=$NIGHTLY_SHA" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image and Publish
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ inputs.image-file }}
          tags: |
            ${{ steps.tag.outputs.nightly }}
            ${{ steps.tag.outputs.nightly-sha }}
