---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Test Madara (hive)

on:
  workflow_call:
    inputs:
      nightly-sha:
        type: string
        required: true

jobs:
  hive-madara:
    runs-on: blacksmith-16vcpu-ubuntu-2204

    steps:
      - name: Download madara
        uses: actions/download-artifact@v4
        with:
          name: madara
          path: ${{ runner.temp }}
      - run: docker load --input ${{ runner.temp }}/madara.tar

      - name: Download openrpc-testgen-runner
        run: docker pull ghcr.io/madara-alliance/openrpc-testgen-runner:v0.1.0

      - name: Setup shared network
        run: docker network create hive

      - name: Start Madara
        run: |
          docker run --rm --network hive -p 9944:9944 --name madara -d ${{ inputs.nightly-sha }} \
            --name madara \
            --devnet \
            --l1-sync-disabled \
            --feeder-gateway-enable \
            --gateway-external \
            --rpc-external \
            --chain-config-override="block_time=2s"

      - name: Start Madara (wait)
        timeout-minutes: 1
        run: |
          until curl -s \
            --location localhost:9944 \
            --header 'Content-Type: application/json' \
            --data '{
                "jsonrpc": "2.0",
                "method": "starknet_blockNumber",
                "params": [],
                "id": 1
            }' &>/dev/null
          do
            sleep 1;
            echo "Retrying...";
          done
          echo "Done!"

      - name: Run Starknet Hive
        run: |
          docker run --rm --network hive ghcr.io/madara-alliance/openrpc-testgen-runner:v0.1.0 \
            --urls "http://madara:9944" \
            --paymaster-account-address "0x055be462e718c4166d656d11f89e341115b8bc82389c3762a10eade04fcb225d" \
            --paymaster-private-key "0x077e56c6dc32d40a67f6f7e6625c8dc5e570abe49c0a24e9202e4ae906abcc07" \
            --udc-address "0x41a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf" \
            --account-class-hash "0xe2eb8f5672af4e6a4e8a8f1b44989685e668489b0a25437733756c5a34a1d6" \
            --suite open-rpc

      - name: Stop Madara
        if: always()
        run: |
          docker stop madara &> /dev/null | true
