---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Run CLI tests

on:
  workflow_call:

jobs:
  test-cli:
    runs-on: blacksmith-8vcpu-ubuntu-2204

    steps:
      - name: Stub
        run: exit 0
