---
name: Task - Test Rust

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      madara-binary-hash:
        description: "Hash used to retrieve the artifact"
        required: true
        type: string
      proptest-cases:
        description: "Number of test cases for property testing"
        required: false
        type: string
        default: "10"
    secrets:
      ETH_FORK_URL:
        required: true

jobs:
  test-rust:
    runs-on: karnot-arc-runner-set
    env:
      ETH_FORK_URL: ${{ secrets.ETH_FORK_URL }}
      PROPTEST_CASES: ${{ inputs.proptest-cases }}
    steps:
      - uses: actions/checkout@v4

      # Setup the environment with all necessary dependencies
      - uses: ./.github/actions/load-env

      - uses: ./.github/actions/rust-setup
        with:
          cache-key: ${{ env.BUILD_RUST_CACHE_KEY }}
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          install-mold: true
          install-scarb: false
          install-foundry: false

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Download Madara binary
        uses: actions/download-artifact@v4
        with:
          name: madara-binary-${{ inputs.madara-binary-hash }}
          path: target/release/
      - run: chmod +x target/release/madara

      - name: Run madara tests (parallel)
        run: |
          cargo nextest run --release --tests --package "mp-*" --package "m-proc-*" --no-fail-fast
      - name: Run madara crate tests (single-threaded)
        run: |
          export COVERAGE_BIN=$(realpath target/release/madara)
          cargo test --release --tests --package "mc-*" --  --test-threads=1
